NMAIN = main
TEX = $(NMAIN).tex

view: build clean
	evince $(NMAIN).pdf &
build:
	latexmk $(TEX)
	dvipdf $(NMAIN).dvi
	
clean: # Cleanup the files generated by LaTeX
	rm $(NMAIN).log $(NMAIN).nav $(NMAIN).snm $(NMAIN).toc $(NMAIN).out $(NMAIN).aux $(NMAIN).dvi

distclean:
	latexmk -C
